---
title: "Mapa de conectividad de grupos funcionales de aves dependientes de bosque en el CBIMA"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
#-------------------- Paquetes --------------------

library(flexdashboard)
library(dplyr)
library(sf)
library(leaflet)
library(esri2sf)

#--------------- URL de geoservicios --------------

url_agfs_teselas <-
  "https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_conectividad_parches_esenciales_importantes_bosque_ma/FeatureServer/0"
url_agfs_rutas <-
  "https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_conectividad_rutas_conectividad_bosque_ma/FeatureServer/0"
url_agfs_limite_cbima <-
  "https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_limite_cbi_maria_aguilar/FeatureServer/0"

#-------------------- Objetos sf -------------------

# Teselas
sf_teselas <- esri2sf(url_agfs_teselas)
# Rutas de conectividad
sf_rutas <- esri2sf(url_agfs_rutas)
# Límite del CBIMA
sf_limite_cbima <- esri2sf(url_agfs_limite_cbima)

#---------------- Paletas de colores ---------------

# Esencialidad
bins_esencialidad <- c(0, 0.0005081, 0.0017842, 0.0029771, 0.0410884, Inf)
labels_esencialidad <- c("Muy poco esencial", "Poco esencial", "Medianamente esencial", "Esencial", "Altamente esencial")
pal_esencialidad <- 
  colorBin(
    bins = bins_esencialidad,
    palette = "Blues", 
    domain = sf_teselas$d_PC,
    n = 5,
  )

# Importancia
bins_importancia <- c(0, 76691858553.50, 419391934883.00, 1873763551120.00, 9206246262880.00, Inf)
labels_importancia <- c("Muy baja importancia", "Importancia baja", "Importancia media", "Alta importancia", "Muy alta importancia")
pal_importancia <- 
  colorBin(
    bins = bins_importancia,
    palette = "Blues", 
    domain = sf_teselas$IF_,
    n = 5,
  )

```

Row
-----------------------------------------------------------------------

### Servicios web: [Teselas esenciales e importantes](https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_conectividad_parches_esenciales_importantes_bripario/FeatureServer), [Rutas de conectividad](https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_conectividad_rutas_conectividad_bosque_ma/FeatureServer)
```{r}
leaflet() %>%
  setView((-84.11961 + -83.97383)/2, (9.907672 + 9.94576)/2, 13) %>%
  addProviderTiles(providers$CartoDB.DarkMatter, group = "CartoDB Dark Matter") %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Stamen Toner Lite") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>%
  addPolygons(
    data = sf_limite_cbima,
    color = "Purple",
    fillColor = "transparent",
    stroke = TRUE,
    weight = 6.0,
    group = "Límite del CBIMA"
  ) %>%
  addPolygons(
    data = sf_teselas,
    fillOpacity = 0.9,
    stroke = TRUE,
    color = ~pal_esencialidad(d_PC),
    fillColor = ~pal_esencialidad(d_PC),
    weight = 0.5,
    smoothFactor = 1.0,
    popup = paste(
              "<strong>Tesela esencial</strong><br>", 
              "Id:", sf_teselas$Id, 
              "<br>", 
              "Esencialidad:", sf_teselas$d_PC
            ),
    group = "Teselas esenciales"
  ) %>%
  addLegend(
    position = "bottomright",
    pal = pal_esencialidad,
    values = sf_teselas$d_PC,
    labFormat = function(type, cuts, p) {paste0(labels_esencialidad)},
    group = "Teselas esenciales",
    title = "Esencialidad"
  ) %>%    
  addPolygons(
    data = sf_teselas,
    fillOpacity = 0.9,
    stroke = TRUE,
    color = ~pal_importancia(IF_),
    fillColor = ~pal_importancia(IF_),
    weight = 0.5,
    smoothFactor = 1.0,
    popup = paste(
              "<strong>Tesela importante</strong><br>", 
              "Id:", sf_teselas$Id, 
              "<br>", 
              "Importancia:", sf_teselas$IF_
            ),
    group = "Teselas importantes"
  ) %>%
  addLegend(
    position = "bottomright",
    pal = pal_importancia,
    values = sf_teselas$IF_,
    labFormat = function(type, cuts, p) {paste0(labels_importancia)},
    group = "Teselas importantes",
    title = "Importancia"
  ) %>%    
  addPolylines(
    data = sf_rutas,
    color = "Green",
    fillColor = "transparent",
    stroke = TRUE,
    weight = 1.5,
    popup = paste(
              "<strong>Ruta de conectividad</strong><br>", 
              "Id:", sf_rutas$Id, 
              "<br>", 
              "Esencialidad:", sf_rutas$d_PC
            ),
    group = "Rutas de conectividad"
  ) %>%
  addLayersControl(
    baseGroups = c("CartoDB Dark Matter", "OpenStreetMap", "Stamen Toner Lite", "Imágenes de ESRI"),
    overlayGroups = c("Límite del CBIMA", "Teselas esenciales", "Teselas importantes", "Rutas de conectividad"),
    options = layersControlOptions(collapsed = TRUE)    
  ) %>%  
  addMiniMap(
    toggleDisplay = TRUE,
    position = "bottomleft",
    tiles = providers$OpenStreetMap.Mapnik
  ) %>%
  addScaleBar(
    position = "bottomleft",
    options = scaleBarOptions(imperial = FALSE)
  ) %>%
  #hideGroup("Teselas esenciales") %>%
  hideGroup("Teselas importantes") %>%
  hideGroup("Rutas de conectividad")
```
